category_index:
  path: /categories
  controller: App\Controller\Category\CategoryAllController
  methods:  [GET]

category_find:
  path: /categories/{id}
  controller: App\Controller\Category\CategoryFindController
  methods:  [GET]

category_create:
  path: /categories/create
  controller: App\Controller\Category\CategoryPostController
  methods:  [POST]

category_delete:
  path: /categories/{id}
  controller: App\Controller\Category\CategoryDeleteController
  methods:  [DELETE]

category_update:
  path: /categories/{id}
  controller: App\Controller\Category\CategoryPutController
  methods:  [PUT]
