doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Magazine/User/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Magazine\User\Domain'
                alias: Category
            Category:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Magazine/Category/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Magazine\Category\Domain'
                alias: Category
            Post:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Magazine/Post/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Magazine\Post\Domain'
                alias: Post
            Comment:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Magazine/Comment/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Magazine\Comment\Domain'
                alias: Comment
