framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus:
                middleware:
                    - doctrine_transaction

            query.bus: ~

            event.bus:
                default_middleware: allow_no_handlers

        transports:
            sync: 'sync://'
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        type: fanout
                        name: 'messages'
   
        routing:
            # Route your messages to the transports
            'App\Magazine\Post\Application\Command\NewPostEmailAdmin\NewPostEmailAdminCommand': async
