version: "3.3"
services:
    # PHP service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-app
        working_dir: /var/www/
        restart: unless-stopped
        volumes:
            - ./:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: symfony server:start

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        restart: unless-stopped
        ports:
            - "3307:3306"
        volumes:
            - ./dbdata/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 12345678
            MYSQL_DATABASE: magazine
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456

    shared_rabbitmq:
        container_name: app-rabbitmq
        image: 'rabbitmq:3.7-management'
        restart: unless-stopped
        ports:
            - 5630:5672
            - 8090:15672
        environment:
            - RABBITMQ_DEFAULT_USER=app
            - RABBITMQ_DEFAULT_PASS=rabbit_app
